// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace BanpoFri.Data
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct CardData : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_5_26(); }
  public static CardData GetRootAsCardData(ByteBuffer _bb) { return GetRootAsCardData(_bb, new CardData()); }
  public static CardData GetRootAsCardData(ByteBuffer _bb, CardData obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public CardData __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int Cardidx { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public bool MutateCardidx(int cardidx) { int o = __p.__offset(4); if (o != 0) { __p.bb.PutInt(o + __p.bb_pos, cardidx); return true; } else { return false; } }
  public int Cardlevel { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public bool MutateCardlevel(int cardlevel) { int o = __p.__offset(6); if (o != 0) { __p.bb.PutInt(o + __p.bb_pos, cardlevel); return true; } else { return false; } }
  public int Cardcount { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public bool MutateCardcount(int cardcount) { int o = __p.__offset(8); if (o != 0) { __p.bb.PutInt(o + __p.bb_pos, cardcount); return true; } else { return false; } }
  public bool Isequip { get { int o = __p.__offset(10); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }
  public bool MutateIsequip(bool isequip) { int o = __p.__offset(10); if (o != 0) { __p.bb.Put(o + __p.bb_pos, (byte)(isequip ? 1 : 0)); return true; } else { return false; } }

  public static Offset<BanpoFri.Data.CardData> CreateCardData(FlatBufferBuilder builder,
      int cardidx = 0,
      int cardlevel = 0,
      int cardcount = 0,
      bool isequip = false) {
    builder.StartTable(4);
    CardData.AddCardcount(builder, cardcount);
    CardData.AddCardlevel(builder, cardlevel);
    CardData.AddCardidx(builder, cardidx);
    CardData.AddIsequip(builder, isequip);
    return CardData.EndCardData(builder);
  }

  public static void StartCardData(FlatBufferBuilder builder) { builder.StartTable(4); }
  public static void AddCardidx(FlatBufferBuilder builder, int cardidx) { builder.AddInt(0, cardidx, 0); }
  public static void AddCardlevel(FlatBufferBuilder builder, int cardlevel) { builder.AddInt(1, cardlevel, 0); }
  public static void AddCardcount(FlatBufferBuilder builder, int cardcount) { builder.AddInt(2, cardcount, 0); }
  public static void AddIsequip(FlatBufferBuilder builder, bool isequip) { builder.AddBool(3, isequip, false); }
  public static Offset<BanpoFri.Data.CardData> EndCardData(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<BanpoFri.Data.CardData>(o);
  }
  public CardDataT UnPack() {
    var _o = new CardDataT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(CardDataT _o) {
    _o.Cardidx = this.Cardidx;
    _o.Cardlevel = this.Cardlevel;
    _o.Cardcount = this.Cardcount;
    _o.Isequip = this.Isequip;
  }
  public static Offset<BanpoFri.Data.CardData> Pack(FlatBufferBuilder builder, CardDataT _o) {
    if (_o == null) return default(Offset<BanpoFri.Data.CardData>);
    return CreateCardData(
      builder,
      _o.Cardidx,
      _o.Cardlevel,
      _o.Cardcount,
      _o.Isequip);
  }
}

public class CardDataT
{
  [Newtonsoft.Json.JsonProperty("cardidx")]
  public int Cardidx { get; set; }
  [Newtonsoft.Json.JsonProperty("cardlevel")]
  public int Cardlevel { get; set; }
  [Newtonsoft.Json.JsonProperty("cardcount")]
  public int Cardcount { get; set; }
  [Newtonsoft.Json.JsonProperty("isequip")]
  public bool Isequip { get; set; }

  public CardDataT() {
    this.Cardidx = 0;
    this.Cardlevel = 0;
    this.Cardcount = 0;
    this.Isequip = false;
  }
}


static public class CardDataVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Cardidx*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 6 /*Cardlevel*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 8 /*Cardcount*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 10 /*Isequip*/, 1 /*bool*/, 1, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
