// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace BanpoFri.Data
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct EquipItemData : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_5_26(); }
  public static EquipItemData GetRootAsEquipItemData(ByteBuffer _bb) { return GetRootAsEquipItemData(_bb, new EquipItemData()); }
  public static EquipItemData GetRootAsEquipItemData(ByteBuffer _bb, EquipItemData obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public EquipItemData __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int Equipitemidx { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public bool MutateEquipitemidx(int equipitemidx) { int o = __p.__offset(4); if (o != 0) { __p.bb.PutInt(o + __p.bb_pos, equipitemidx); return true; } else { return false; } }
  public int Level { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public bool MutateLevel(int level) { int o = __p.__offset(6); if (o != 0) { __p.bb.PutInt(o + __p.bb_pos, level); return true; } else { return false; } }
  public int Grade { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public bool MutateGrade(int grade) { int o = __p.__offset(8); if (o != 0) { __p.bb.PutInt(o + __p.bb_pos, grade); return true; } else { return false; } }

  public static Offset<BanpoFri.Data.EquipItemData> CreateEquipItemData(FlatBufferBuilder builder,
      int equipitemidx = 0,
      int level = 0,
      int grade = 0) {
    builder.StartTable(3);
    EquipItemData.AddGrade(builder, grade);
    EquipItemData.AddLevel(builder, level);
    EquipItemData.AddEquipitemidx(builder, equipitemidx);
    return EquipItemData.EndEquipItemData(builder);
  }

  public static void StartEquipItemData(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void AddEquipitemidx(FlatBufferBuilder builder, int equipitemidx) { builder.AddInt(0, equipitemidx, 0); }
  public static void AddLevel(FlatBufferBuilder builder, int level) { builder.AddInt(1, level, 0); }
  public static void AddGrade(FlatBufferBuilder builder, int grade) { builder.AddInt(2, grade, 0); }
  public static Offset<BanpoFri.Data.EquipItemData> EndEquipItemData(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<BanpoFri.Data.EquipItemData>(o);
  }
  public EquipItemDataT UnPack() {
    var _o = new EquipItemDataT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(EquipItemDataT _o) {
    _o.Equipitemidx = this.Equipitemidx;
    _o.Level = this.Level;
    _o.Grade = this.Grade;
  }
  public static Offset<BanpoFri.Data.EquipItemData> Pack(FlatBufferBuilder builder, EquipItemDataT _o) {
    if (_o == null) return default(Offset<BanpoFri.Data.EquipItemData>);
    return CreateEquipItemData(
      builder,
      _o.Equipitemidx,
      _o.Level,
      _o.Grade);
  }
}

public class EquipItemDataT
{
  [Newtonsoft.Json.JsonProperty("equipitemidx")]
  public int Equipitemidx { get; set; }
  [Newtonsoft.Json.JsonProperty("level")]
  public int Level { get; set; }
  [Newtonsoft.Json.JsonProperty("grade")]
  public int Grade { get; set; }

  public EquipItemDataT() {
    this.Equipitemidx = 0;
    this.Level = 0;
    this.Grade = 0;
  }
}


static public class EquipItemDataVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Equipitemidx*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 6 /*Level*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 8 /*Grade*/, 4 /*int*/, 4, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
