// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace BanpoFri.Data
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct HeroItemData : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_5_26(); }
  public static HeroItemData GetRootAsHeroItemData(ByteBuffer _bb) { return GetRootAsHeroItemData(_bb, new HeroItemData()); }
  public static HeroItemData GetRootAsHeroItemData(ByteBuffer _bb, HeroItemData obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public HeroItemData __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int Heroitemidx { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public bool MutateHeroitemidx(int heroitemidx) { int o = __p.__offset(4); if (o != 0) { __p.bb.PutInt(o + __p.bb_pos, heroitemidx); return true; } else { return false; } }
  public int Grade { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public bool MutateGrade(int grade) { int o = __p.__offset(6); if (o != 0) { __p.bb.PutInt(o + __p.bb_pos, grade); return true; } else { return false; } }
  public bool Isequip { get { int o = __p.__offset(8); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }
  public bool MutateIsequip(bool isequip) { int o = __p.__offset(8); if (o != 0) { __p.bb.Put(o + __p.bb_pos, (byte)(isequip ? 1 : 0)); return true; } else { return false; } }

  public static Offset<BanpoFri.Data.HeroItemData> CreateHeroItemData(FlatBufferBuilder builder,
      int heroitemidx = 0,
      int grade = 0,
      bool isequip = false) {
    builder.StartTable(3);
    HeroItemData.AddGrade(builder, grade);
    HeroItemData.AddHeroitemidx(builder, heroitemidx);
    HeroItemData.AddIsequip(builder, isequip);
    return HeroItemData.EndHeroItemData(builder);
  }

  public static void StartHeroItemData(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void AddHeroitemidx(FlatBufferBuilder builder, int heroitemidx) { builder.AddInt(0, heroitemidx, 0); }
  public static void AddGrade(FlatBufferBuilder builder, int grade) { builder.AddInt(1, grade, 0); }
  public static void AddIsequip(FlatBufferBuilder builder, bool isequip) { builder.AddBool(2, isequip, false); }
  public static Offset<BanpoFri.Data.HeroItemData> EndHeroItemData(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<BanpoFri.Data.HeroItemData>(o);
  }
  public HeroItemDataT UnPack() {
    var _o = new HeroItemDataT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(HeroItemDataT _o) {
    _o.Heroitemidx = this.Heroitemidx;
    _o.Grade = this.Grade;
    _o.Isequip = this.Isequip;
  }
  public static Offset<BanpoFri.Data.HeroItemData> Pack(FlatBufferBuilder builder, HeroItemDataT _o) {
    if (_o == null) return default(Offset<BanpoFri.Data.HeroItemData>);
    return CreateHeroItemData(
      builder,
      _o.Heroitemidx,
      _o.Grade,
      _o.Isequip);
  }
}

public class HeroItemDataT
{
  [Newtonsoft.Json.JsonProperty("heroitemidx")]
  public int Heroitemidx { get; set; }
  [Newtonsoft.Json.JsonProperty("grade")]
  public int Grade { get; set; }
  [Newtonsoft.Json.JsonProperty("isequip")]
  public bool Isequip { get; set; }

  public HeroItemDataT() {
    this.Heroitemidx = 0;
    this.Grade = 0;
    this.Isequip = false;
  }
}


static public class HeroItemDataVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Heroitemidx*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 6 /*Grade*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 8 /*Isequip*/, 1 /*bool*/, 1, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
