// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace BanpoFri.Data
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct HeroGroupData : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_5_26(); }
  public static HeroGroupData GetRootAsHeroGroupData(ByteBuffer _bb) { return GetRootAsHeroGroupData(_bb, new HeroGroupData()); }
  public static HeroGroupData GetRootAsHeroGroupData(ByteBuffer _bb, HeroGroupData obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public HeroGroupData __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int Equipplayeridx { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public bool MutateEquipplayeridx(int equipplayeridx) { int o = __p.__offset(4); if (o != 0) { __p.bb.PutInt(o + __p.bb_pos, equipplayeridx); return true; } else { return false; } }
  public BanpoFri.Data.HeroEquipItemData? Equipheroitems(int j) { int o = __p.__offset(6); return o != 0 ? (BanpoFri.Data.HeroEquipItemData?)(new BanpoFri.Data.HeroEquipItemData()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int EquipheroitemsLength { get { int o = __p.__offset(6); return o != 0 ? __p.__vector_len(o) : 0; } }
  public BanpoFri.Data.HeroItemData? Heroitemdatas(int j) { int o = __p.__offset(8); return o != 0 ? (BanpoFri.Data.HeroItemData?)(new BanpoFri.Data.HeroItemData()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int HeroitemdatasLength { get { int o = __p.__offset(8); return o != 0 ? __p.__vector_len(o) : 0; } }
  public int Herolevel { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public bool MutateHerolevel(int herolevel) { int o = __p.__offset(10); if (o != 0) { __p.bb.PutInt(o + __p.bb_pos, herolevel); return true; } else { return false; } }

  public static Offset<BanpoFri.Data.HeroGroupData> CreateHeroGroupData(FlatBufferBuilder builder,
      int equipplayeridx = 0,
      VectorOffset equipheroitemsOffset = default(VectorOffset),
      VectorOffset heroitemdatasOffset = default(VectorOffset),
      int herolevel = 0) {
    builder.StartTable(4);
    HeroGroupData.AddHerolevel(builder, herolevel);
    HeroGroupData.AddHeroitemdatas(builder, heroitemdatasOffset);
    HeroGroupData.AddEquipheroitems(builder, equipheroitemsOffset);
    HeroGroupData.AddEquipplayeridx(builder, equipplayeridx);
    return HeroGroupData.EndHeroGroupData(builder);
  }

  public static void StartHeroGroupData(FlatBufferBuilder builder) { builder.StartTable(4); }
  public static void AddEquipplayeridx(FlatBufferBuilder builder, int equipplayeridx) { builder.AddInt(0, equipplayeridx, 0); }
  public static void AddEquipheroitems(FlatBufferBuilder builder, VectorOffset equipheroitemsOffset) { builder.AddOffset(1, equipheroitemsOffset.Value, 0); }
  public static VectorOffset CreateEquipheroitemsVector(FlatBufferBuilder builder, Offset<BanpoFri.Data.HeroEquipItemData>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateEquipheroitemsVectorBlock(FlatBufferBuilder builder, Offset<BanpoFri.Data.HeroEquipItemData>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateEquipheroitemsVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<BanpoFri.Data.HeroEquipItemData>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateEquipheroitemsVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<BanpoFri.Data.HeroEquipItemData>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartEquipheroitemsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddHeroitemdatas(FlatBufferBuilder builder, VectorOffset heroitemdatasOffset) { builder.AddOffset(2, heroitemdatasOffset.Value, 0); }
  public static VectorOffset CreateHeroitemdatasVector(FlatBufferBuilder builder, Offset<BanpoFri.Data.HeroItemData>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateHeroitemdatasVectorBlock(FlatBufferBuilder builder, Offset<BanpoFri.Data.HeroItemData>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateHeroitemdatasVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<BanpoFri.Data.HeroItemData>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateHeroitemdatasVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<BanpoFri.Data.HeroItemData>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartHeroitemdatasVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddHerolevel(FlatBufferBuilder builder, int herolevel) { builder.AddInt(3, herolevel, 0); }
  public static Offset<BanpoFri.Data.HeroGroupData> EndHeroGroupData(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<BanpoFri.Data.HeroGroupData>(o);
  }
  public HeroGroupDataT UnPack() {
    var _o = new HeroGroupDataT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(HeroGroupDataT _o) {
    _o.Equipplayeridx = this.Equipplayeridx;
    _o.Equipheroitems = new List<BanpoFri.Data.HeroEquipItemDataT>();
    for (var _j = 0; _j < this.EquipheroitemsLength; ++_j) {_o.Equipheroitems.Add(this.Equipheroitems(_j).HasValue ? this.Equipheroitems(_j).Value.UnPack() : null);}
    _o.Heroitemdatas = new List<BanpoFri.Data.HeroItemDataT>();
    for (var _j = 0; _j < this.HeroitemdatasLength; ++_j) {_o.Heroitemdatas.Add(this.Heroitemdatas(_j).HasValue ? this.Heroitemdatas(_j).Value.UnPack() : null);}
    _o.Herolevel = this.Herolevel;
  }
  public static Offset<BanpoFri.Data.HeroGroupData> Pack(FlatBufferBuilder builder, HeroGroupDataT _o) {
    if (_o == null) return default(Offset<BanpoFri.Data.HeroGroupData>);
    var _equipheroitems = default(VectorOffset);
    if (_o.Equipheroitems != null) {
      var __equipheroitems = new Offset<BanpoFri.Data.HeroEquipItemData>[_o.Equipheroitems.Count];
      for (var _j = 0; _j < __equipheroitems.Length; ++_j) { __equipheroitems[_j] = BanpoFri.Data.HeroEquipItemData.Pack(builder, _o.Equipheroitems[_j]); }
      _equipheroitems = CreateEquipheroitemsVector(builder, __equipheroitems);
    }
    var _heroitemdatas = default(VectorOffset);
    if (_o.Heroitemdatas != null) {
      var __heroitemdatas = new Offset<BanpoFri.Data.HeroItemData>[_o.Heroitemdatas.Count];
      for (var _j = 0; _j < __heroitemdatas.Length; ++_j) { __heroitemdatas[_j] = BanpoFri.Data.HeroItemData.Pack(builder, _o.Heroitemdatas[_j]); }
      _heroitemdatas = CreateHeroitemdatasVector(builder, __heroitemdatas);
    }
    return CreateHeroGroupData(
      builder,
      _o.Equipplayeridx,
      _equipheroitems,
      _heroitemdatas,
      _o.Herolevel);
  }
}

public class HeroGroupDataT
{
  [Newtonsoft.Json.JsonProperty("equipplayeridx")]
  public int Equipplayeridx { get; set; }
  [Newtonsoft.Json.JsonProperty("equipheroitems")]
  public List<BanpoFri.Data.HeroEquipItemDataT> Equipheroitems { get; set; }
  [Newtonsoft.Json.JsonProperty("heroitemdatas")]
  public List<BanpoFri.Data.HeroItemDataT> Heroitemdatas { get; set; }
  [Newtonsoft.Json.JsonProperty("herolevel")]
  public int Herolevel { get; set; }

  public HeroGroupDataT() {
    this.Equipplayeridx = 0;
    this.Equipheroitems = null;
    this.Heroitemdatas = null;
    this.Herolevel = 0;
  }
}


static public class HeroGroupDataVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Equipplayeridx*/, 4 /*int*/, 4, false)
      && verifier.VerifyVectorOfTables(tablePos, 6 /*Equipheroitems*/, BanpoFri.Data.HeroEquipItemDataVerify.Verify, false)
      && verifier.VerifyVectorOfTables(tablePos, 8 /*Heroitemdatas*/, BanpoFri.Data.HeroItemDataVerify.Verify, false)
      && verifier.VerifyField(tablePos, 10 /*Herolevel*/, 4 /*int*/, 4, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
