// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace BanpoFri.Data
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct HeroEquipItemData : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_5_26(); }
  public static HeroEquipItemData GetRootAsHeroEquipItemData(ByteBuffer _bb) { return GetRootAsHeroEquipItemData(_bb, new HeroEquipItemData()); }
  public static HeroEquipItemData GetRootAsHeroEquipItemData(ByteBuffer _bb, HeroEquipItemData obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public HeroEquipItemData __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public bool Isequip { get { int o = __p.__offset(4); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }
  public bool MutateIsequip(bool isequip) { int o = __p.__offset(4); if (o != 0) { __p.bb.Put(o + __p.bb_pos, (byte)(isequip ? 1 : 0)); return true; } else { return false; } }
  public int Level { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public bool MutateLevel(int level) { int o = __p.__offset(6); if (o != 0) { __p.bb.PutInt(o + __p.bb_pos, level); return true; } else { return false; } }
  public int Heroitemtype { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public bool MutateHeroitemtype(int heroitemtype) { int o = __p.__offset(8); if (o != 0) { __p.bb.PutInt(o + __p.bb_pos, heroitemtype); return true; } else { return false; } }

  public static Offset<BanpoFri.Data.HeroEquipItemData> CreateHeroEquipItemData(FlatBufferBuilder builder,
      bool isequip = false,
      int level = 0,
      int heroitemtype = 0) {
    builder.StartTable(3);
    HeroEquipItemData.AddHeroitemtype(builder, heroitemtype);
    HeroEquipItemData.AddLevel(builder, level);
    HeroEquipItemData.AddIsequip(builder, isequip);
    return HeroEquipItemData.EndHeroEquipItemData(builder);
  }

  public static void StartHeroEquipItemData(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void AddIsequip(FlatBufferBuilder builder, bool isequip) { builder.AddBool(0, isequip, false); }
  public static void AddLevel(FlatBufferBuilder builder, int level) { builder.AddInt(1, level, 0); }
  public static void AddHeroitemtype(FlatBufferBuilder builder, int heroitemtype) { builder.AddInt(2, heroitemtype, 0); }
  public static Offset<BanpoFri.Data.HeroEquipItemData> EndHeroEquipItemData(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<BanpoFri.Data.HeroEquipItemData>(o);
  }
  public HeroEquipItemDataT UnPack() {
    var _o = new HeroEquipItemDataT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(HeroEquipItemDataT _o) {
    _o.Isequip = this.Isequip;
    _o.Level = this.Level;
    _o.Heroitemtype = this.Heroitemtype;
  }
  public static Offset<BanpoFri.Data.HeroEquipItemData> Pack(FlatBufferBuilder builder, HeroEquipItemDataT _o) {
    if (_o == null) return default(Offset<BanpoFri.Data.HeroEquipItemData>);
    return CreateHeroEquipItemData(
      builder,
      _o.Isequip,
      _o.Level,
      _o.Heroitemtype);
  }
}

public class HeroEquipItemDataT
{
  [Newtonsoft.Json.JsonProperty("isequip")]
  public bool Isequip { get; set; }
  [Newtonsoft.Json.JsonProperty("level")]
  public int Level { get; set; }
  [Newtonsoft.Json.JsonProperty("heroitemtype")]
  public int Heroitemtype { get; set; }

  public HeroEquipItemDataT() {
    this.Isequip = false;
    this.Level = 0;
    this.Heroitemtype = 0;
  }
}


static public class HeroEquipItemDataVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Isequip*/, 1 /*bool*/, 1, false)
      && verifier.VerifyField(tablePos, 6 /*Level*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 8 /*Heroitemtype*/, 4 /*int*/, 4, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
