// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace BanpoFri.Data
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct InGameResumeTileData : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_5_26(); }
  public static InGameResumeTileData GetRootAsInGameResumeTileData(ByteBuffer _bb) { return GetRootAsInGameResumeTileData(_bb, new InGameResumeTileData()); }
  public static InGameResumeTileData GetRootAsInGameResumeTileData(ByteBuffer _bb, InGameResumeTileData obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public InGameResumeTileData __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int Equipidx { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public bool MutateEquipidx(int equipidx) { int o = __p.__offset(4); if (o != 0) { __p.bb.PutInt(o + __p.bb_pos, equipidx); return true; } else { return false; } }
  public int Grade { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)1; } }
  public bool MutateGrade(int grade) { int o = __p.__offset(6); if (o != 0) { __p.bb.PutInt(o + __p.bb_pos, grade); return true; } else { return false; } }
  public int Tileorder { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)-1; } }
  public bool MutateTileorder(int tileorder) { int o = __p.__offset(8); if (o != 0) { __p.bb.PutInt(o + __p.bb_pos, tileorder); return true; } else { return false; } }
  public bool Isad { get { int o = __p.__offset(10); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }
  public bool MutateIsad(bool isad) { int o = __p.__offset(10); if (o != 0) { __p.bb.Put(o + __p.bb_pos, (byte)(isad ? 1 : 0)); return true; } else { return false; } }

  public static Offset<BanpoFri.Data.InGameResumeTileData> CreateInGameResumeTileData(FlatBufferBuilder builder,
      int equipidx = 0,
      int grade = 1,
      int tileorder = -1,
      bool isad = false) {
    builder.StartTable(4);
    InGameResumeTileData.AddTileorder(builder, tileorder);
    InGameResumeTileData.AddGrade(builder, grade);
    InGameResumeTileData.AddEquipidx(builder, equipidx);
    InGameResumeTileData.AddIsad(builder, isad);
    return InGameResumeTileData.EndInGameResumeTileData(builder);
  }

  public static void StartInGameResumeTileData(FlatBufferBuilder builder) { builder.StartTable(4); }
  public static void AddEquipidx(FlatBufferBuilder builder, int equipidx) { builder.AddInt(0, equipidx, 0); }
  public static void AddGrade(FlatBufferBuilder builder, int grade) { builder.AddInt(1, grade, 1); }
  public static void AddTileorder(FlatBufferBuilder builder, int tileorder) { builder.AddInt(2, tileorder, -1); }
  public static void AddIsad(FlatBufferBuilder builder, bool isad) { builder.AddBool(3, isad, false); }
  public static Offset<BanpoFri.Data.InGameResumeTileData> EndInGameResumeTileData(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<BanpoFri.Data.InGameResumeTileData>(o);
  }
  public InGameResumeTileDataT UnPack() {
    var _o = new InGameResumeTileDataT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(InGameResumeTileDataT _o) {
    _o.Equipidx = this.Equipidx;
    _o.Grade = this.Grade;
    _o.Tileorder = this.Tileorder;
    _o.Isad = this.Isad;
  }
  public static Offset<BanpoFri.Data.InGameResumeTileData> Pack(FlatBufferBuilder builder, InGameResumeTileDataT _o) {
    if (_o == null) return default(Offset<BanpoFri.Data.InGameResumeTileData>);
    return CreateInGameResumeTileData(
      builder,
      _o.Equipidx,
      _o.Grade,
      _o.Tileorder,
      _o.Isad);
  }
}

public class InGameResumeTileDataT
{
  [Newtonsoft.Json.JsonProperty("equipidx")]
  public int Equipidx { get; set; }
  [Newtonsoft.Json.JsonProperty("grade")]
  public int Grade { get; set; }
  [Newtonsoft.Json.JsonProperty("tileorder")]
  public int Tileorder { get; set; }
  [Newtonsoft.Json.JsonProperty("isad")]
  public bool Isad { get; set; }

  public InGameResumeTileDataT() {
    this.Equipidx = 0;
    this.Grade = 1;
    this.Tileorder = -1;
    this.Isad = false;
  }
}


static public class InGameResumeTileDataVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Equipidx*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 6 /*Grade*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 8 /*Tileorder*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 10 /*Isad*/, 1 /*bool*/, 1, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
