// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace BanpoFri.Data
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct InGameResumeData : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_5_26(); }
  public static InGameResumeData GetRootAsInGameResumeData(ByteBuffer _bb) { return GetRootAsInGameResumeData(_bb, new InGameResumeData()); }
  public static InGameResumeData GetRootAsInGameResumeData(ByteBuffer _bb, InGameResumeData obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public InGameResumeData __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public bool Isvalid { get { int o = __p.__offset(4); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }
  public bool MutateIsvalid(bool isvalid) { int o = __p.__offset(4); if (o != 0) { __p.bb.Put(o + __p.bb_pos, (byte)(isvalid ? 1 : 0)); return true; } else { return false; } }
  public int Stageidx { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public bool MutateStageidx(int stageidx) { int o = __p.__offset(6); if (o != 0) { __p.bb.PutInt(o + __p.bb_pos, stageidx); return true; } else { return false; } }
  public int Waveidx { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public bool MutateWaveidx(int waveidx) { int o = __p.__offset(8); if (o != 0) { __p.bb.PutInt(o + __p.bb_pos, waveidx); return true; } else { return false; } }
  public int Silvercoin { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public bool MutateSilvercoin(int silvercoin) { int o = __p.__offset(10); if (o != 0) { __p.bb.PutInt(o + __p.bb_pos, silvercoin); return true; } else { return false; } }
  public int Hp { get { int o = __p.__offset(12); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public bool MutateHp(int hp) { int o = __p.__offset(12); if (o != 0) { __p.bb.PutInt(o + __p.bb_pos, hp); return true; } else { return false; } }
  public BanpoFri.Data.InGameResumeTileData? Tiles(int j) { int o = __p.__offset(14); return o != 0 ? (BanpoFri.Data.InGameResumeTileData?)(new BanpoFri.Data.InGameResumeTileData()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int TilesLength { get { int o = __p.__offset(14); return o != 0 ? __p.__vector_len(o) : 0; } }
  public int Starthp { get { int o = __p.__offset(16); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public bool MutateStarthp(int starthp) { int o = __p.__offset(16); if (o != 0) { __p.bb.PutInt(o + __p.bb_pos, starthp); return true; } else { return false; } }
  public int Shield { get { int o = __p.__offset(18); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public bool MutateShield(int shield) { int o = __p.__offset(18); if (o != 0) { __p.bb.PutInt(o + __p.bb_pos, shield); return true; } else { return false; } }
  public int Killcount { get { int o = __p.__offset(20); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public bool MutateKillcount(int killcount) { int o = __p.__offset(20); if (o != 0) { __p.bb.PutInt(o + __p.bb_pos, killcount); return true; } else { return false; } }
  public int Ingameexp { get { int o = __p.__offset(22); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public bool MutateIngameexp(int ingameexp) { int o = __p.__offset(22); if (o != 0) { __p.bb.PutInt(o + __p.bb_pos, ingameexp); return true; } else { return false; } }
  public int Upgradecount { get { int o = __p.__offset(24); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)1; } }
  public bool MutateUpgradecount(int upgradecount) { int o = __p.__offset(24); if (o != 0) { __p.bb.PutInt(o + __p.bb_pos, upgradecount); return true; } else { return false; } }
  public int Ingamemoney { get { int o = __p.__offset(26); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public bool MutateIngamemoney(int ingamemoney) { int o = __p.__offset(26); if (o != 0) { __p.bb.PutInt(o + __p.bb_pos, ingamemoney); return true; } else { return false; } }
  public int Rerollcount { get { int o = __p.__offset(28); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public bool MutateRerollcount(int rerollcount) { int o = __p.__offset(28); if (o != 0) { __p.bb.PutInt(o + __p.bb_pos, rerollcount); return true; } else { return false; } }
  public int Unlockedtiles(int j) { int o = __p.__offset(30); return o != 0 ? __p.bb.GetInt(__p.__vector(o) + j * 4) : (int)0; }
  public int UnlockedtilesLength { get { int o = __p.__offset(30); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<int> GetUnlockedtilesBytes() { return __p.__vector_as_span<int>(30, 4); }
#else
  public ArraySegment<byte>? GetUnlockedtilesBytes() { return __p.__vector_as_arraysegment(30); }
#endif
  public int[] GetUnlockedtilesArray() { return __p.__vector_as_array<int>(30); }
  public bool MutateUnlockedtiles(int j, int unlockedtiles) { int o = __p.__offset(30); if (o != 0) { __p.bb.PutInt(__p.__vector(o) + j * 4, unlockedtiles); return true; } else { return false; } }
  public int Upgradeindices(int j) { int o = __p.__offset(32); return o != 0 ? __p.bb.GetInt(__p.__vector(o) + j * 4) : (int)0; }
  public int UpgradeindicesLength { get { int o = __p.__offset(32); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<int> GetUpgradeindicesBytes() { return __p.__vector_as_span<int>(32, 4); }
#else
  public ArraySegment<byte>? GetUpgradeindicesBytes() { return __p.__vector_as_arraysegment(32); }
#endif
  public int[] GetUpgradeindicesArray() { return __p.__vector_as_array<int>(32); }
  public bool MutateUpgradeindices(int j, int upgradeindices) { int o = __p.__offset(32); if (o != 0) { __p.bb.PutInt(__p.__vector(o) + j * 4, upgradeindices); return true; } else { return false; } }

  public static Offset<BanpoFri.Data.InGameResumeData> CreateInGameResumeData(FlatBufferBuilder builder,
      bool isvalid = false,
      int stageidx = 0,
      int waveidx = 0,
      int silvercoin = 0,
      int hp = 0,
      VectorOffset tilesOffset = default(VectorOffset),
      int starthp = 0,
      int shield = 0,
      int killcount = 0,
      int ingameexp = 0,
      int upgradecount = 1,
      int ingamemoney = 0,
      int rerollcount = 0,
      VectorOffset unlockedtilesOffset = default(VectorOffset),
      VectorOffset upgradeindicesOffset = default(VectorOffset)) {
    builder.StartTable(15);
    InGameResumeData.AddUpgradeindices(builder, upgradeindicesOffset);
    InGameResumeData.AddUnlockedtiles(builder, unlockedtilesOffset);
    InGameResumeData.AddRerollcount(builder, rerollcount);
    InGameResumeData.AddIngamemoney(builder, ingamemoney);
    InGameResumeData.AddUpgradecount(builder, upgradecount);
    InGameResumeData.AddIngameexp(builder, ingameexp);
    InGameResumeData.AddKillcount(builder, killcount);
    InGameResumeData.AddShield(builder, shield);
    InGameResumeData.AddStarthp(builder, starthp);
    InGameResumeData.AddTiles(builder, tilesOffset);
    InGameResumeData.AddHp(builder, hp);
    InGameResumeData.AddSilvercoin(builder, silvercoin);
    InGameResumeData.AddWaveidx(builder, waveidx);
    InGameResumeData.AddStageidx(builder, stageidx);
    InGameResumeData.AddIsvalid(builder, isvalid);
    return InGameResumeData.EndInGameResumeData(builder);
  }

  public static void StartInGameResumeData(FlatBufferBuilder builder) { builder.StartTable(15); }
  public static void AddIsvalid(FlatBufferBuilder builder, bool isvalid) { builder.AddBool(0, isvalid, false); }
  public static void AddStageidx(FlatBufferBuilder builder, int stageidx) { builder.AddInt(1, stageidx, 0); }
  public static void AddWaveidx(FlatBufferBuilder builder, int waveidx) { builder.AddInt(2, waveidx, 0); }
  public static void AddSilvercoin(FlatBufferBuilder builder, int silvercoin) { builder.AddInt(3, silvercoin, 0); }
  public static void AddHp(FlatBufferBuilder builder, int hp) { builder.AddInt(4, hp, 0); }
  public static void AddTiles(FlatBufferBuilder builder, VectorOffset tilesOffset) { builder.AddOffset(5, tilesOffset.Value, 0); }
  public static VectorOffset CreateTilesVector(FlatBufferBuilder builder, Offset<BanpoFri.Data.InGameResumeTileData>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateTilesVectorBlock(FlatBufferBuilder builder, Offset<BanpoFri.Data.InGameResumeTileData>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateTilesVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<BanpoFri.Data.InGameResumeTileData>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateTilesVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<BanpoFri.Data.InGameResumeTileData>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartTilesVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddStarthp(FlatBufferBuilder builder, int starthp) { builder.AddInt(6, starthp, 0); }
  public static void AddShield(FlatBufferBuilder builder, int shield) { builder.AddInt(7, shield, 0); }
  public static void AddKillcount(FlatBufferBuilder builder, int killcount) { builder.AddInt(8, killcount, 0); }
  public static void AddIngameexp(FlatBufferBuilder builder, int ingameexp) { builder.AddInt(9, ingameexp, 0); }
  public static void AddUpgradecount(FlatBufferBuilder builder, int upgradecount) { builder.AddInt(10, upgradecount, 1); }
  public static void AddIngamemoney(FlatBufferBuilder builder, int ingamemoney) { builder.AddInt(11, ingamemoney, 0); }
  public static void AddRerollcount(FlatBufferBuilder builder, int rerollcount) { builder.AddInt(12, rerollcount, 0); }
  public static void AddUnlockedtiles(FlatBufferBuilder builder, VectorOffset unlockedtilesOffset) { builder.AddOffset(13, unlockedtilesOffset.Value, 0); }
  public static VectorOffset CreateUnlockedtilesVector(FlatBufferBuilder builder, int[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddInt(data[i]); return builder.EndVector(); }
  public static VectorOffset CreateUnlockedtilesVectorBlock(FlatBufferBuilder builder, int[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateUnlockedtilesVectorBlock(FlatBufferBuilder builder, ArraySegment<int> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateUnlockedtilesVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<int>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartUnlockedtilesVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddUpgradeindices(FlatBufferBuilder builder, VectorOffset upgradeindicesOffset) { builder.AddOffset(14, upgradeindicesOffset.Value, 0); }
  public static VectorOffset CreateUpgradeindicesVector(FlatBufferBuilder builder, int[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddInt(data[i]); return builder.EndVector(); }
  public static VectorOffset CreateUpgradeindicesVectorBlock(FlatBufferBuilder builder, int[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateUpgradeindicesVectorBlock(FlatBufferBuilder builder, ArraySegment<int> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateUpgradeindicesVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<int>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartUpgradeindicesVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<BanpoFri.Data.InGameResumeData> EndInGameResumeData(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<BanpoFri.Data.InGameResumeData>(o);
  }
  public InGameResumeDataT UnPack() {
    var _o = new InGameResumeDataT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(InGameResumeDataT _o) {
    _o.Isvalid = this.Isvalid;
    _o.Stageidx = this.Stageidx;
    _o.Waveidx = this.Waveidx;
    _o.Silvercoin = this.Silvercoin;
    _o.Hp = this.Hp;
    _o.Tiles = new List<BanpoFri.Data.InGameResumeTileDataT>();
    for (var _j = 0; _j < this.TilesLength; ++_j) {_o.Tiles.Add(this.Tiles(_j).HasValue ? this.Tiles(_j).Value.UnPack() : null);}
    _o.Starthp = this.Starthp;
    _o.Shield = this.Shield;
    _o.Killcount = this.Killcount;
    _o.Ingameexp = this.Ingameexp;
    _o.Upgradecount = this.Upgradecount;
    _o.Ingamemoney = this.Ingamemoney;
    _o.Rerollcount = this.Rerollcount;
    _o.Unlockedtiles = new List<int>();
    for (var _j = 0; _j < this.UnlockedtilesLength; ++_j) {_o.Unlockedtiles.Add(this.Unlockedtiles(_j));}
    _o.Upgradeindices = new List<int>();
    for (var _j = 0; _j < this.UpgradeindicesLength; ++_j) {_o.Upgradeindices.Add(this.Upgradeindices(_j));}
  }
  public static Offset<BanpoFri.Data.InGameResumeData> Pack(FlatBufferBuilder builder, InGameResumeDataT _o) {
    if (_o == null) return default(Offset<BanpoFri.Data.InGameResumeData>);
    var _tiles = default(VectorOffset);
    if (_o.Tiles != null) {
      var __tiles = new Offset<BanpoFri.Data.InGameResumeTileData>[_o.Tiles.Count];
      for (var _j = 0; _j < __tiles.Length; ++_j) { __tiles[_j] = BanpoFri.Data.InGameResumeTileData.Pack(builder, _o.Tiles[_j]); }
      _tiles = CreateTilesVector(builder, __tiles);
    }
    var _unlockedtiles = default(VectorOffset);
    if (_o.Unlockedtiles != null) {
      var __unlockedtiles = _o.Unlockedtiles.ToArray();
      _unlockedtiles = CreateUnlockedtilesVector(builder, __unlockedtiles);
    }
    var _upgradeindices = default(VectorOffset);
    if (_o.Upgradeindices != null) {
      var __upgradeindices = _o.Upgradeindices.ToArray();
      _upgradeindices = CreateUpgradeindicesVector(builder, __upgradeindices);
    }
    return CreateInGameResumeData(
      builder,
      _o.Isvalid,
      _o.Stageidx,
      _o.Waveidx,
      _o.Silvercoin,
      _o.Hp,
      _tiles,
      _o.Starthp,
      _o.Shield,
      _o.Killcount,
      _o.Ingameexp,
      _o.Upgradecount,
      _o.Ingamemoney,
      _o.Rerollcount,
      _unlockedtiles,
      _upgradeindices);
  }
}

public class InGameResumeDataT
{
  [Newtonsoft.Json.JsonProperty("isvalid")]
  public bool Isvalid { get; set; }
  [Newtonsoft.Json.JsonProperty("stageidx")]
  public int Stageidx { get; set; }
  [Newtonsoft.Json.JsonProperty("waveidx")]
  public int Waveidx { get; set; }
  [Newtonsoft.Json.JsonProperty("silvercoin")]
  public int Silvercoin { get; set; }
  [Newtonsoft.Json.JsonProperty("hp")]
  public int Hp { get; set; }
  [Newtonsoft.Json.JsonProperty("tiles")]
  public List<BanpoFri.Data.InGameResumeTileDataT> Tiles { get; set; }
  [Newtonsoft.Json.JsonProperty("starthp")]
  public int Starthp { get; set; }
  [Newtonsoft.Json.JsonProperty("shield")]
  public int Shield { get; set; }
  [Newtonsoft.Json.JsonProperty("killcount")]
  public int Killcount { get; set; }
  [Newtonsoft.Json.JsonProperty("ingameexp")]
  public int Ingameexp { get; set; }
  [Newtonsoft.Json.JsonProperty("upgradecount")]
  public int Upgradecount { get; set; }
  [Newtonsoft.Json.JsonProperty("ingamemoney")]
  public int Ingamemoney { get; set; }
  [Newtonsoft.Json.JsonProperty("rerollcount")]
  public int Rerollcount { get; set; }
  [Newtonsoft.Json.JsonProperty("unlockedtiles")]
  public List<int> Unlockedtiles { get; set; }
  [Newtonsoft.Json.JsonProperty("upgradeindices")]
  public List<int> Upgradeindices { get; set; }

  public InGameResumeDataT() {
    this.Isvalid = false;
    this.Stageidx = 0;
    this.Waveidx = 0;
    this.Silvercoin = 0;
    this.Hp = 0;
    this.Tiles = null;
    this.Starthp = 0;
    this.Shield = 0;
    this.Killcount = 0;
    this.Ingameexp = 0;
    this.Upgradecount = 1;
    this.Ingamemoney = 0;
    this.Rerollcount = 0;
    this.Unlockedtiles = null;
    this.Upgradeindices = null;
  }
}


static public class InGameResumeDataVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Isvalid*/, 1 /*bool*/, 1, false)
      && verifier.VerifyField(tablePos, 6 /*Stageidx*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 8 /*Waveidx*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 10 /*Silvercoin*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 12 /*Hp*/, 4 /*int*/, 4, false)
      && verifier.VerifyVectorOfTables(tablePos, 14 /*Tiles*/, BanpoFri.Data.InGameResumeTileDataVerify.Verify, false)
      && verifier.VerifyField(tablePos, 16 /*Starthp*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 18 /*Shield*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 20 /*Killcount*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 22 /*Ingameexp*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 24 /*Upgradecount*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 26 /*Ingamemoney*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 28 /*Rerollcount*/, 4 /*int*/, 4, false)
      && verifier.VerifyVectorOfData(tablePos, 30 /*Unlockedtiles*/, 4 /*int*/, false)
      && verifier.VerifyVectorOfData(tablePos, 32 /*Upgradeindices*/, 4 /*int*/, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
