// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace BanpoFri.Data
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct ItemData : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_5_26(); }
  public static ItemData GetRootAsItemData(ByteBuffer _bb) { return GetRootAsItemData(_bb, new ItemData()); }
  public static ItemData GetRootAsItemData(ByteBuffer _bb, ItemData obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public ItemData __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int Itemtype { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public bool MutateItemtype(int itemtype) { int o = __p.__offset(4); if (o != 0) { __p.bb.PutInt(o + __p.bb_pos, itemtype); return true; } else { return false; } }
  public int Itemidx { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public bool MutateItemidx(int itemidx) { int o = __p.__offset(6); if (o != 0) { __p.bb.PutInt(o + __p.bb_pos, itemidx); return true; } else { return false; } }
  public int Itemcnt { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public bool MutateItemcnt(int itemcnt) { int o = __p.__offset(8); if (o != 0) { __p.bb.PutInt(o + __p.bb_pos, itemcnt); return true; } else { return false; } }

  public static Offset<BanpoFri.Data.ItemData> CreateItemData(FlatBufferBuilder builder,
      int itemtype = 0,
      int itemidx = 0,
      int itemcnt = 0) {
    builder.StartTable(3);
    ItemData.AddItemcnt(builder, itemcnt);
    ItemData.AddItemidx(builder, itemidx);
    ItemData.AddItemtype(builder, itemtype);
    return ItemData.EndItemData(builder);
  }

  public static void StartItemData(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void AddItemtype(FlatBufferBuilder builder, int itemtype) { builder.AddInt(0, itemtype, 0); }
  public static void AddItemidx(FlatBufferBuilder builder, int itemidx) { builder.AddInt(1, itemidx, 0); }
  public static void AddItemcnt(FlatBufferBuilder builder, int itemcnt) { builder.AddInt(2, itemcnt, 0); }
  public static Offset<BanpoFri.Data.ItemData> EndItemData(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<BanpoFri.Data.ItemData>(o);
  }
  public ItemDataT UnPack() {
    var _o = new ItemDataT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(ItemDataT _o) {
    _o.Itemtype = this.Itemtype;
    _o.Itemidx = this.Itemidx;
    _o.Itemcnt = this.Itemcnt;
  }
  public static Offset<BanpoFri.Data.ItemData> Pack(FlatBufferBuilder builder, ItemDataT _o) {
    if (_o == null) return default(Offset<BanpoFri.Data.ItemData>);
    return CreateItemData(
      builder,
      _o.Itemtype,
      _o.Itemidx,
      _o.Itemcnt);
  }
}

public class ItemDataT
{
  [Newtonsoft.Json.JsonProperty("itemtype")]
  public int Itemtype { get; set; }
  [Newtonsoft.Json.JsonProperty("itemidx")]
  public int Itemidx { get; set; }
  [Newtonsoft.Json.JsonProperty("itemcnt")]
  public int Itemcnt { get; set; }

  public ItemDataT() {
    this.Itemtype = 0;
    this.Itemidx = 0;
    this.Itemcnt = 0;
  }
}


static public class ItemDataVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Itemtype*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 6 /*Itemidx*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 8 /*Itemcnt*/, 4 /*int*/, 4, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
