// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace BanpoFri.Data
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct PlayerEquipData : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_5_26(); }
  public static PlayerEquipData GetRootAsPlayerEquipData(ByteBuffer _bb) { return GetRootAsPlayerEquipData(_bb, new PlayerEquipData()); }
  public static PlayerEquipData GetRootAsPlayerEquipData(ByteBuffer _bb, PlayerEquipData obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public PlayerEquipData __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public BanpoFri.Data.EquipItemData? Equipitemdatas(int j) { int o = __p.__offset(4); return o != 0 ? (BanpoFri.Data.EquipItemData?)(new BanpoFri.Data.EquipItemData()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int EquipitemdatasLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<BanpoFri.Data.PlayerEquipData> CreatePlayerEquipData(FlatBufferBuilder builder,
      VectorOffset equipitemdatasOffset = default(VectorOffset)) {
    builder.StartTable(1);
    PlayerEquipData.AddEquipitemdatas(builder, equipitemdatasOffset);
    return PlayerEquipData.EndPlayerEquipData(builder);
  }

  public static void StartPlayerEquipData(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddEquipitemdatas(FlatBufferBuilder builder, VectorOffset equipitemdatasOffset) { builder.AddOffset(0, equipitemdatasOffset.Value, 0); }
  public static VectorOffset CreateEquipitemdatasVector(FlatBufferBuilder builder, Offset<BanpoFri.Data.EquipItemData>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateEquipitemdatasVectorBlock(FlatBufferBuilder builder, Offset<BanpoFri.Data.EquipItemData>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateEquipitemdatasVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<BanpoFri.Data.EquipItemData>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateEquipitemdatasVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<BanpoFri.Data.EquipItemData>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartEquipitemdatasVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<BanpoFri.Data.PlayerEquipData> EndPlayerEquipData(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<BanpoFri.Data.PlayerEquipData>(o);
  }
  public PlayerEquipDataT UnPack() {
    var _o = new PlayerEquipDataT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(PlayerEquipDataT _o) {
    _o.Equipitemdatas = new List<BanpoFri.Data.EquipItemDataT>();
    for (var _j = 0; _j < this.EquipitemdatasLength; ++_j) {_o.Equipitemdatas.Add(this.Equipitemdatas(_j).HasValue ? this.Equipitemdatas(_j).Value.UnPack() : null);}
  }
  public static Offset<BanpoFri.Data.PlayerEquipData> Pack(FlatBufferBuilder builder, PlayerEquipDataT _o) {
    if (_o == null) return default(Offset<BanpoFri.Data.PlayerEquipData>);
    var _equipitemdatas = default(VectorOffset);
    if (_o.Equipitemdatas != null) {
      var __equipitemdatas = new Offset<BanpoFri.Data.EquipItemData>[_o.Equipitemdatas.Count];
      for (var _j = 0; _j < __equipitemdatas.Length; ++_j) { __equipitemdatas[_j] = BanpoFri.Data.EquipItemData.Pack(builder, _o.Equipitemdatas[_j]); }
      _equipitemdatas = CreateEquipitemdatasVector(builder, __equipitemdatas);
    }
    return CreatePlayerEquipData(
      builder,
      _equipitemdatas);
  }
}

public class PlayerEquipDataT
{
  [Newtonsoft.Json.JsonProperty("equipitemdatas")]
  public List<BanpoFri.Data.EquipItemDataT> Equipitemdatas { get; set; }

  public PlayerEquipDataT() {
    this.Equipitemdatas = null;
  }
}


static public class PlayerEquipDataVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyVectorOfTables(tablePos, 4 /*Equipitemdatas*/, BanpoFri.Data.EquipItemDataVerify.Verify, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
