// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace BanpoFri.Data
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct PlayerData : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_5_26(); }
  public static PlayerData GetRootAsPlayerData(ByteBuffer _bb) { return GetRootAsPlayerData(_bb, new PlayerData()); }
  public static PlayerData GetRootAsPlayerData(ByteBuffer _bb, PlayerData obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public PlayerData __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int Playerlevel { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)1; } }
  public bool MutatePlayerlevel(int playerlevel) { int o = __p.__offset(4); if (o != 0) { __p.bb.PutInt(o + __p.bb_pos, playerlevel); return true; } else { return false; } }
  public int Playerexp { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)1; } }
  public bool MutatePlayerexp(int playerexp) { int o = __p.__offset(6); if (o != 0) { __p.bb.PutInt(o + __p.bb_pos, playerexp); return true; } else { return false; } }
  public string Playername { get { int o = __p.__offset(8); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetPlayernameBytes() { return __p.__vector_as_span<byte>(8, 1); }
#else
  public ArraySegment<byte>? GetPlayernameBytes() { return __p.__vector_as_arraysegment(8); }
#endif
  public byte[] GetPlayernameArray() { return __p.__vector_as_array<byte>(8); }

  public static Offset<BanpoFri.Data.PlayerData> CreatePlayerData(FlatBufferBuilder builder,
      int playerlevel = 1,
      int playerexp = 1,
      StringOffset playernameOffset = default(StringOffset)) {
    builder.StartTable(3);
    PlayerData.AddPlayername(builder, playernameOffset);
    PlayerData.AddPlayerexp(builder, playerexp);
    PlayerData.AddPlayerlevel(builder, playerlevel);
    return PlayerData.EndPlayerData(builder);
  }

  public static void StartPlayerData(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void AddPlayerlevel(FlatBufferBuilder builder, int playerlevel) { builder.AddInt(0, playerlevel, 1); }
  public static void AddPlayerexp(FlatBufferBuilder builder, int playerexp) { builder.AddInt(1, playerexp, 1); }
  public static void AddPlayername(FlatBufferBuilder builder, StringOffset playernameOffset) { builder.AddOffset(2, playernameOffset.Value, 0); }
  public static Offset<BanpoFri.Data.PlayerData> EndPlayerData(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<BanpoFri.Data.PlayerData>(o);
  }
  public PlayerDataT UnPack() {
    var _o = new PlayerDataT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(PlayerDataT _o) {
    _o.Playerlevel = this.Playerlevel;
    _o.Playerexp = this.Playerexp;
    _o.Playername = this.Playername;
  }
  public static Offset<BanpoFri.Data.PlayerData> Pack(FlatBufferBuilder builder, PlayerDataT _o) {
    if (_o == null) return default(Offset<BanpoFri.Data.PlayerData>);
    var _playername = _o.Playername == null ? default(StringOffset) : builder.CreateString(_o.Playername);
    return CreatePlayerData(
      builder,
      _o.Playerlevel,
      _o.Playerexp,
      _playername);
  }
}

public class PlayerDataT
{
  [Newtonsoft.Json.JsonProperty("playerlevel")]
  public int Playerlevel { get; set; }
  [Newtonsoft.Json.JsonProperty("playerexp")]
  public int Playerexp { get; set; }
  [Newtonsoft.Json.JsonProperty("playername")]
  public string Playername { get; set; }

  public PlayerDataT() {
    this.Playerlevel = 1;
    this.Playerexp = 1;
    this.Playername = null;
  }
}


static public class PlayerDataVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Playerlevel*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 6 /*Playerexp*/, 4 /*int*/, 4, false)
      && verifier.VerifyString(tablePos, 8 /*Playername*/, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
