// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace BanpoFri.Data
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct StageRewardBoxGroupData : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_5_26(); }
  public static StageRewardBoxGroupData GetRootAsStageRewardBoxGroupData(ByteBuffer _bb) { return GetRootAsStageRewardBoxGroupData(_bb, new StageRewardBoxGroupData()); }
  public static StageRewardBoxGroupData GetRootAsStageRewardBoxGroupData(ByteBuffer _bb, StageRewardBoxGroupData obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public StageRewardBoxGroupData __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public BanpoFri.Data.StageRewardBoxData? Stagerewardboxdatas(int j) { int o = __p.__offset(4); return o != 0 ? (BanpoFri.Data.StageRewardBoxData?)(new BanpoFri.Data.StageRewardBoxData()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int StagerewardboxdatasLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }
  public int Boxcount { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public bool MutateBoxcount(int boxcount) { int o = __p.__offset(6); if (o != 0) { __p.bb.PutInt(o + __p.bb_pos, boxcount); return true; } else { return false; } }
  public int Equipitembox(int j) { int o = __p.__offset(8); return o != 0 ? __p.bb.GetInt(__p.__vector(o) + j * 4) : (int)0; }
  public int EquipitemboxLength { get { int o = __p.__offset(8); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<int> GetEquipitemboxBytes() { return __p.__vector_as_span<int>(8, 4); }
#else
  public ArraySegment<byte>? GetEquipitemboxBytes() { return __p.__vector_as_arraysegment(8); }
#endif
  public int[] GetEquipitemboxArray() { return __p.__vector_as_array<int>(8); }
  public bool MutateEquipitembox(int j, int equipitembox) { int o = __p.__offset(8); if (o != 0) { __p.bb.PutInt(__p.__vector(o) + j * 4, equipitembox); return true; } else { return false; } }

  public static Offset<BanpoFri.Data.StageRewardBoxGroupData> CreateStageRewardBoxGroupData(FlatBufferBuilder builder,
      VectorOffset stagerewardboxdatasOffset = default(VectorOffset),
      int boxcount = 0,
      VectorOffset equipitemboxOffset = default(VectorOffset)) {
    builder.StartTable(3);
    StageRewardBoxGroupData.AddEquipitembox(builder, equipitemboxOffset);
    StageRewardBoxGroupData.AddBoxcount(builder, boxcount);
    StageRewardBoxGroupData.AddStagerewardboxdatas(builder, stagerewardboxdatasOffset);
    return StageRewardBoxGroupData.EndStageRewardBoxGroupData(builder);
  }

  public static void StartStageRewardBoxGroupData(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void AddStagerewardboxdatas(FlatBufferBuilder builder, VectorOffset stagerewardboxdatasOffset) { builder.AddOffset(0, stagerewardboxdatasOffset.Value, 0); }
  public static VectorOffset CreateStagerewardboxdatasVector(FlatBufferBuilder builder, Offset<BanpoFri.Data.StageRewardBoxData>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateStagerewardboxdatasVectorBlock(FlatBufferBuilder builder, Offset<BanpoFri.Data.StageRewardBoxData>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateStagerewardboxdatasVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<BanpoFri.Data.StageRewardBoxData>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateStagerewardboxdatasVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<BanpoFri.Data.StageRewardBoxData>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartStagerewardboxdatasVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddBoxcount(FlatBufferBuilder builder, int boxcount) { builder.AddInt(1, boxcount, 0); }
  public static void AddEquipitembox(FlatBufferBuilder builder, VectorOffset equipitemboxOffset) { builder.AddOffset(2, equipitemboxOffset.Value, 0); }
  public static VectorOffset CreateEquipitemboxVector(FlatBufferBuilder builder, int[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddInt(data[i]); return builder.EndVector(); }
  public static VectorOffset CreateEquipitemboxVectorBlock(FlatBufferBuilder builder, int[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateEquipitemboxVectorBlock(FlatBufferBuilder builder, ArraySegment<int> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateEquipitemboxVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<int>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartEquipitemboxVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<BanpoFri.Data.StageRewardBoxGroupData> EndStageRewardBoxGroupData(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<BanpoFri.Data.StageRewardBoxGroupData>(o);
  }
  public StageRewardBoxGroupDataT UnPack() {
    var _o = new StageRewardBoxGroupDataT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(StageRewardBoxGroupDataT _o) {
    _o.Stagerewardboxdatas = new List<BanpoFri.Data.StageRewardBoxDataT>();
    for (var _j = 0; _j < this.StagerewardboxdatasLength; ++_j) {_o.Stagerewardboxdatas.Add(this.Stagerewardboxdatas(_j).HasValue ? this.Stagerewardboxdatas(_j).Value.UnPack() : null);}
    _o.Boxcount = this.Boxcount;
    _o.Equipitembox = new List<int>();
    for (var _j = 0; _j < this.EquipitemboxLength; ++_j) {_o.Equipitembox.Add(this.Equipitembox(_j));}
  }
  public static Offset<BanpoFri.Data.StageRewardBoxGroupData> Pack(FlatBufferBuilder builder, StageRewardBoxGroupDataT _o) {
    if (_o == null) return default(Offset<BanpoFri.Data.StageRewardBoxGroupData>);
    var _stagerewardboxdatas = default(VectorOffset);
    if (_o.Stagerewardboxdatas != null) {
      var __stagerewardboxdatas = new Offset<BanpoFri.Data.StageRewardBoxData>[_o.Stagerewardboxdatas.Count];
      for (var _j = 0; _j < __stagerewardboxdatas.Length; ++_j) { __stagerewardboxdatas[_j] = BanpoFri.Data.StageRewardBoxData.Pack(builder, _o.Stagerewardboxdatas[_j]); }
      _stagerewardboxdatas = CreateStagerewardboxdatasVector(builder, __stagerewardboxdatas);
    }
    var _equipitembox = default(VectorOffset);
    if (_o.Equipitembox != null) {
      var __equipitembox = _o.Equipitembox.ToArray();
      _equipitembox = CreateEquipitemboxVector(builder, __equipitembox);
    }
    return CreateStageRewardBoxGroupData(
      builder,
      _stagerewardboxdatas,
      _o.Boxcount,
      _equipitembox);
  }
}

public class StageRewardBoxGroupDataT
{
  [Newtonsoft.Json.JsonProperty("stagerewardboxdatas")]
  public List<BanpoFri.Data.StageRewardBoxDataT> Stagerewardboxdatas { get; set; }
  [Newtonsoft.Json.JsonProperty("boxcount")]
  public int Boxcount { get; set; }
  [Newtonsoft.Json.JsonProperty("equipitembox")]
  public List<int> Equipitembox { get; set; }

  public StageRewardBoxGroupDataT() {
    this.Stagerewardboxdatas = null;
    this.Boxcount = 0;
    this.Equipitembox = null;
  }
}


static public class StageRewardBoxGroupDataVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyVectorOfTables(tablePos, 4 /*Stagerewardboxdatas*/, BanpoFri.Data.StageRewardBoxDataVerify.Verify, false)
      && verifier.VerifyField(tablePos, 6 /*Boxcount*/, 4 /*int*/, 4, false)
      && verifier.VerifyVectorOfData(tablePos, 8 /*Equipitembox*/, 4 /*int*/, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
