// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace BanpoFri.Data
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct StageRewardBoxData : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_5_26(); }
  public static StageRewardBoxData GetRootAsStageRewardBoxData(ByteBuffer _bb) { return GetRootAsStageRewardBoxData(_bb, new StageRewardBoxData()); }
  public static StageRewardBoxData GetRootAsStageRewardBoxData(ByteBuffer _bb, StageRewardBoxData obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public StageRewardBoxData __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int Boxidx { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public bool MutateBoxidx(int boxidx) { int o = __p.__offset(4); if (o != 0) { __p.bb.PutInt(o + __p.bb_pos, boxidx); return true; } else { return false; } }
  public long Boxtime { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public bool MutateBoxtime(long boxtime) { int o = __p.__offset(6); if (o != 0) { __p.bb.PutLong(o + __p.bb_pos, boxtime); return true; } else { return false; } }
  public bool Isopenstart { get { int o = __p.__offset(8); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }
  public bool MutateIsopenstart(bool isopenstart) { int o = __p.__offset(8); if (o != 0) { __p.bb.Put(o + __p.bb_pos, (byte)(isopenstart ? 1 : 0)); return true; } else { return false; } }
  public int Boxorder { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public bool MutateBoxorder(int boxorder) { int o = __p.__offset(10); if (o != 0) { __p.bb.PutInt(o + __p.bb_pos, boxorder); return true; } else { return false; } }
  public int Boxgetstageidx { get { int o = __p.__offset(12); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public bool MutateBoxgetstageidx(int boxgetstageidx) { int o = __p.__offset(12); if (o != 0) { __p.bb.PutInt(o + __p.bb_pos, boxgetstageidx); return true; } else { return false; } }

  public static Offset<BanpoFri.Data.StageRewardBoxData> CreateStageRewardBoxData(FlatBufferBuilder builder,
      int boxidx = 0,
      long boxtime = 0,
      bool isopenstart = false,
      int boxorder = 0,
      int boxgetstageidx = 0) {
    builder.StartTable(5);
    StageRewardBoxData.AddBoxtime(builder, boxtime);
    StageRewardBoxData.AddBoxgetstageidx(builder, boxgetstageidx);
    StageRewardBoxData.AddBoxorder(builder, boxorder);
    StageRewardBoxData.AddBoxidx(builder, boxidx);
    StageRewardBoxData.AddIsopenstart(builder, isopenstart);
    return StageRewardBoxData.EndStageRewardBoxData(builder);
  }

  public static void StartStageRewardBoxData(FlatBufferBuilder builder) { builder.StartTable(5); }
  public static void AddBoxidx(FlatBufferBuilder builder, int boxidx) { builder.AddInt(0, boxidx, 0); }
  public static void AddBoxtime(FlatBufferBuilder builder, long boxtime) { builder.AddLong(1, boxtime, 0); }
  public static void AddIsopenstart(FlatBufferBuilder builder, bool isopenstart) { builder.AddBool(2, isopenstart, false); }
  public static void AddBoxorder(FlatBufferBuilder builder, int boxorder) { builder.AddInt(3, boxorder, 0); }
  public static void AddBoxgetstageidx(FlatBufferBuilder builder, int boxgetstageidx) { builder.AddInt(4, boxgetstageidx, 0); }
  public static Offset<BanpoFri.Data.StageRewardBoxData> EndStageRewardBoxData(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<BanpoFri.Data.StageRewardBoxData>(o);
  }
  public StageRewardBoxDataT UnPack() {
    var _o = new StageRewardBoxDataT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(StageRewardBoxDataT _o) {
    _o.Boxidx = this.Boxidx;
    _o.Boxtime = this.Boxtime;
    _o.Isopenstart = this.Isopenstart;
    _o.Boxorder = this.Boxorder;
    _o.Boxgetstageidx = this.Boxgetstageidx;
  }
  public static Offset<BanpoFri.Data.StageRewardBoxData> Pack(FlatBufferBuilder builder, StageRewardBoxDataT _o) {
    if (_o == null) return default(Offset<BanpoFri.Data.StageRewardBoxData>);
    return CreateStageRewardBoxData(
      builder,
      _o.Boxidx,
      _o.Boxtime,
      _o.Isopenstart,
      _o.Boxorder,
      _o.Boxgetstageidx);
  }
}

public class StageRewardBoxDataT
{
  [Newtonsoft.Json.JsonProperty("boxidx")]
  public int Boxidx { get; set; }
  [Newtonsoft.Json.JsonProperty("boxtime")]
  public long Boxtime { get; set; }
  [Newtonsoft.Json.JsonProperty("isopenstart")]
  public bool Isopenstart { get; set; }
  [Newtonsoft.Json.JsonProperty("boxorder")]
  public int Boxorder { get; set; }
  [Newtonsoft.Json.JsonProperty("boxgetstageidx")]
  public int Boxgetstageidx { get; set; }

  public StageRewardBoxDataT() {
    this.Boxidx = 0;
    this.Boxtime = 0;
    this.Isopenstart = false;
    this.Boxorder = 0;
    this.Boxgetstageidx = 0;
  }
}


static public class StageRewardBoxDataVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Boxidx*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 6 /*Boxtime*/, 8 /*long*/, 8, false)
      && verifier.VerifyField(tablePos, 8 /*Isopenstart*/, 1 /*bool*/, 1, false)
      && verifier.VerifyField(tablePos, 10 /*Boxorder*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 12 /*Boxgetstageidx*/, 4 /*int*/, 4, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
