// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace BanpoFri.Data
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct StarterPackageData : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_5_26(); }
  public static StarterPackageData GetRootAsStarterPackageData(ByteBuffer _bb) { return GetRootAsStarterPackageData(_bb, new StarterPackageData()); }
  public static StarterPackageData GetRootAsStarterPackageData(ByteBuffer _bb, StarterPackageData obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public StarterPackageData __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public bool Isbuy { get { int o = __p.__offset(4); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }
  public bool MutateIsbuy(bool isbuy) { int o = __p.__offset(4); if (o != 0) { __p.bb.Put(o + __p.bb_pos, (byte)(isbuy ? 1 : 0)); return true; } else { return false; } }
  public long Starterpackbuytime { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public bool MutateStarterpackbuytime(long starterpackbuytime) { int o = __p.__offset(6); if (o != 0) { __p.bb.PutLong(o + __p.bb_pos, starterpackbuytime); return true; } else { return false; } }

  public static Offset<BanpoFri.Data.StarterPackageData> CreateStarterPackageData(FlatBufferBuilder builder,
      bool isbuy = false,
      long starterpackbuytime = 0) {
    builder.StartTable(2);
    StarterPackageData.AddStarterpackbuytime(builder, starterpackbuytime);
    StarterPackageData.AddIsbuy(builder, isbuy);
    return StarterPackageData.EndStarterPackageData(builder);
  }

  public static void StartStarterPackageData(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddIsbuy(FlatBufferBuilder builder, bool isbuy) { builder.AddBool(0, isbuy, false); }
  public static void AddStarterpackbuytime(FlatBufferBuilder builder, long starterpackbuytime) { builder.AddLong(1, starterpackbuytime, 0); }
  public static Offset<BanpoFri.Data.StarterPackageData> EndStarterPackageData(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<BanpoFri.Data.StarterPackageData>(o);
  }
  public StarterPackageDataT UnPack() {
    var _o = new StarterPackageDataT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(StarterPackageDataT _o) {
    _o.Isbuy = this.Isbuy;
    _o.Starterpackbuytime = this.Starterpackbuytime;
  }
  public static Offset<BanpoFri.Data.StarterPackageData> Pack(FlatBufferBuilder builder, StarterPackageDataT _o) {
    if (_o == null) return default(Offset<BanpoFri.Data.StarterPackageData>);
    return CreateStarterPackageData(
      builder,
      _o.Isbuy,
      _o.Starterpackbuytime);
  }
}

public class StarterPackageDataT
{
  [Newtonsoft.Json.JsonProperty("isbuy")]
  public bool Isbuy { get; set; }
  [Newtonsoft.Json.JsonProperty("starterpackbuytime")]
  public long Starterpackbuytime { get; set; }

  public StarterPackageDataT() {
    this.Isbuy = false;
    this.Starterpackbuytime = 0;
  }
}


static public class StarterPackageDataVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Isbuy*/, 1 /*bool*/, 1, false)
      && verifier.VerifyField(tablePos, 6 /*Starterpackbuytime*/, 8 /*long*/, 8, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
