// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace BanpoFri.Data
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct TrainingData : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_5_26(); }
  public static TrainingData GetRootAsTrainingData(ByteBuffer _bb) { return GetRootAsTrainingData(_bb, new TrainingData()); }
  public static TrainingData GetRootAsTrainingData(ByteBuffer _bb, TrainingData obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public TrainingData __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int Trainingorder { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)1; } }
  public bool MutateTrainingorder(int trainingorder) { int o = __p.__offset(4); if (o != 0) { __p.bb.PutInt(o + __p.bb_pos, trainingorder); return true; } else { return false; } }
  public bool Isupgradeproperty { get { int o = __p.__offset(6); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }
  public bool MutateIsupgradeproperty(bool isupgradeproperty) { int o = __p.__offset(6); if (o != 0) { __p.bb.Put(o + __p.bb_pos, (byte)(isupgradeproperty ? 1 : 0)); return true; } else { return false; } }
  public bool Specialisupgradeproperty { get { int o = __p.__offset(8); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }
  public bool MutateSpecialisupgradeproperty(bool specialisupgradeproperty) { int o = __p.__offset(8); if (o != 0) { __p.bb.Put(o + __p.bb_pos, (byte)(specialisupgradeproperty ? 1 : 0)); return true; } else { return false; } }
  public int Traininglevel { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)1; } }
  public bool MutateTraininglevel(int traininglevel) { int o = __p.__offset(10); if (o != 0) { __p.bb.PutInt(o + __p.bb_pos, traininglevel); return true; } else { return false; } }

  public static Offset<BanpoFri.Data.TrainingData> CreateTrainingData(FlatBufferBuilder builder,
      int trainingorder = 1,
      bool isupgradeproperty = false,
      bool specialisupgradeproperty = false,
      int traininglevel = 1) {
    builder.StartTable(4);
    TrainingData.AddTraininglevel(builder, traininglevel);
    TrainingData.AddTrainingorder(builder, trainingorder);
    TrainingData.AddSpecialisupgradeproperty(builder, specialisupgradeproperty);
    TrainingData.AddIsupgradeproperty(builder, isupgradeproperty);
    return TrainingData.EndTrainingData(builder);
  }

  public static void StartTrainingData(FlatBufferBuilder builder) { builder.StartTable(4); }
  public static void AddTrainingorder(FlatBufferBuilder builder, int trainingorder) { builder.AddInt(0, trainingorder, 1); }
  public static void AddIsupgradeproperty(FlatBufferBuilder builder, bool isupgradeproperty) { builder.AddBool(1, isupgradeproperty, false); }
  public static void AddSpecialisupgradeproperty(FlatBufferBuilder builder, bool specialisupgradeproperty) { builder.AddBool(2, specialisupgradeproperty, false); }
  public static void AddTraininglevel(FlatBufferBuilder builder, int traininglevel) { builder.AddInt(3, traininglevel, 1); }
  public static Offset<BanpoFri.Data.TrainingData> EndTrainingData(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<BanpoFri.Data.TrainingData>(o);
  }
  public TrainingDataT UnPack() {
    var _o = new TrainingDataT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(TrainingDataT _o) {
    _o.Trainingorder = this.Trainingorder;
    _o.Isupgradeproperty = this.Isupgradeproperty;
    _o.Specialisupgradeproperty = this.Specialisupgradeproperty;
    _o.Traininglevel = this.Traininglevel;
  }
  public static Offset<BanpoFri.Data.TrainingData> Pack(FlatBufferBuilder builder, TrainingDataT _o) {
    if (_o == null) return default(Offset<BanpoFri.Data.TrainingData>);
    return CreateTrainingData(
      builder,
      _o.Trainingorder,
      _o.Isupgradeproperty,
      _o.Specialisupgradeproperty,
      _o.Traininglevel);
  }
}

public class TrainingDataT
{
  [Newtonsoft.Json.JsonProperty("trainingorder")]
  public int Trainingorder { get; set; }
  [Newtonsoft.Json.JsonProperty("isupgradeproperty")]
  public bool Isupgradeproperty { get; set; }
  [Newtonsoft.Json.JsonProperty("specialisupgradeproperty")]
  public bool Specialisupgradeproperty { get; set; }
  [Newtonsoft.Json.JsonProperty("traininglevel")]
  public int Traininglevel { get; set; }

  public TrainingDataT() {
    this.Trainingorder = 1;
    this.Isupgradeproperty = false;
    this.Specialisupgradeproperty = false;
    this.Traininglevel = 1;
  }
}


static public class TrainingDataVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Trainingorder*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 6 /*Isupgradeproperty*/, 1 /*bool*/, 1, false)
      && verifier.VerifyField(tablePos, 8 /*Specialisupgradeproperty*/, 1 /*bool*/, 1, false)
      && verifier.VerifyField(tablePos, 10 /*Traininglevel*/, 4 /*int*/, 4, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
