// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace BanpoFri.Data
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct TrainingGroupData : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_5_26(); }
  public static TrainingGroupData GetRootAsTrainingGroupData(ByteBuffer _bb) { return GetRootAsTrainingGroupData(_bb, new TrainingGroupData()); }
  public static TrainingGroupData GetRootAsTrainingGroupData(ByteBuffer _bb, TrainingGroupData obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public TrainingGroupData __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public BanpoFri.Data.TrainingData? Trainingdatas(int j) { int o = __p.__offset(4); return o != 0 ? (BanpoFri.Data.TrainingData?)(new BanpoFri.Data.TrainingData()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int TrainingdatasLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }
  public int Classlevel { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public bool MutateClasslevel(int classlevel) { int o = __p.__offset(6); if (o != 0) { __p.bb.PutInt(o + __p.bb_pos, classlevel); return true; } else { return false; } }

  public static Offset<BanpoFri.Data.TrainingGroupData> CreateTrainingGroupData(FlatBufferBuilder builder,
      VectorOffset trainingdatasOffset = default(VectorOffset),
      int classlevel = 0) {
    builder.StartTable(2);
    TrainingGroupData.AddClasslevel(builder, classlevel);
    TrainingGroupData.AddTrainingdatas(builder, trainingdatasOffset);
    return TrainingGroupData.EndTrainingGroupData(builder);
  }

  public static void StartTrainingGroupData(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddTrainingdatas(FlatBufferBuilder builder, VectorOffset trainingdatasOffset) { builder.AddOffset(0, trainingdatasOffset.Value, 0); }
  public static VectorOffset CreateTrainingdatasVector(FlatBufferBuilder builder, Offset<BanpoFri.Data.TrainingData>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateTrainingdatasVectorBlock(FlatBufferBuilder builder, Offset<BanpoFri.Data.TrainingData>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateTrainingdatasVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<BanpoFri.Data.TrainingData>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateTrainingdatasVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<BanpoFri.Data.TrainingData>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartTrainingdatasVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddClasslevel(FlatBufferBuilder builder, int classlevel) { builder.AddInt(1, classlevel, 0); }
  public static Offset<BanpoFri.Data.TrainingGroupData> EndTrainingGroupData(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<BanpoFri.Data.TrainingGroupData>(o);
  }
  public TrainingGroupDataT UnPack() {
    var _o = new TrainingGroupDataT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(TrainingGroupDataT _o) {
    _o.Trainingdatas = new List<BanpoFri.Data.TrainingDataT>();
    for (var _j = 0; _j < this.TrainingdatasLength; ++_j) {_o.Trainingdatas.Add(this.Trainingdatas(_j).HasValue ? this.Trainingdatas(_j).Value.UnPack() : null);}
    _o.Classlevel = this.Classlevel;
  }
  public static Offset<BanpoFri.Data.TrainingGroupData> Pack(FlatBufferBuilder builder, TrainingGroupDataT _o) {
    if (_o == null) return default(Offset<BanpoFri.Data.TrainingGroupData>);
    var _trainingdatas = default(VectorOffset);
    if (_o.Trainingdatas != null) {
      var __trainingdatas = new Offset<BanpoFri.Data.TrainingData>[_o.Trainingdatas.Count];
      for (var _j = 0; _j < __trainingdatas.Length; ++_j) { __trainingdatas[_j] = BanpoFri.Data.TrainingData.Pack(builder, _o.Trainingdatas[_j]); }
      _trainingdatas = CreateTrainingdatasVector(builder, __trainingdatas);
    }
    return CreateTrainingGroupData(
      builder,
      _trainingdatas,
      _o.Classlevel);
  }
}

public class TrainingGroupDataT
{
  [Newtonsoft.Json.JsonProperty("trainingdatas")]
  public List<BanpoFri.Data.TrainingDataT> Trainingdatas { get; set; }
  [Newtonsoft.Json.JsonProperty("classlevel")]
  public int Classlevel { get; set; }

  public TrainingGroupDataT() {
    this.Trainingdatas = null;
    this.Classlevel = 0;
  }
}


static public class TrainingGroupDataVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyVectorOfTables(tablePos, 4 /*Trainingdatas*/, BanpoFri.Data.TrainingDataVerify.Verify, false)
      && verifier.VerifyField(tablePos, 6 /*Classlevel*/, 4 /*int*/, 4, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
