// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace BanpoFri.Data
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct UnitGroupData : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_5_26(); }
  public static UnitGroupData GetRootAsUnitGroupData(ByteBuffer _bb) { return GetRootAsUnitGroupData(_bb, new UnitGroupData()); }
  public static UnitGroupData GetRootAsUnitGroupData(ByteBuffer _bb, UnitGroupData obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public UnitGroupData __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int Equipidxs(int j) { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(__p.__vector(o) + j * 4) : (int)0; }
  public int EquipidxsLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<int> GetEquipidxsBytes() { return __p.__vector_as_span<int>(4, 4); }
#else
  public ArraySegment<byte>? GetEquipidxsBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public int[] GetEquipidxsArray() { return __p.__vector_as_array<int>(4); }
  public bool MutateEquipidxs(int j, int equipidxs) { int o = __p.__offset(4); if (o != 0) { __p.bb.PutInt(__p.__vector(o) + j * 4, equipidxs); return true; } else { return false; } }
  public BanpoFri.Data.UnitData? Unitdatas(int j) { int o = __p.__offset(6); return o != 0 ? (BanpoFri.Data.UnitData?)(new BanpoFri.Data.UnitData()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int UnitdatasLength { get { int o = __p.__offset(6); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<BanpoFri.Data.UnitGroupData> CreateUnitGroupData(FlatBufferBuilder builder,
      VectorOffset equipidxsOffset = default(VectorOffset),
      VectorOffset unitdatasOffset = default(VectorOffset)) {
    builder.StartTable(2);
    UnitGroupData.AddUnitdatas(builder, unitdatasOffset);
    UnitGroupData.AddEquipidxs(builder, equipidxsOffset);
    return UnitGroupData.EndUnitGroupData(builder);
  }

  public static void StartUnitGroupData(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddEquipidxs(FlatBufferBuilder builder, VectorOffset equipidxsOffset) { builder.AddOffset(0, equipidxsOffset.Value, 0); }
  public static VectorOffset CreateEquipidxsVector(FlatBufferBuilder builder, int[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddInt(data[i]); return builder.EndVector(); }
  public static VectorOffset CreateEquipidxsVectorBlock(FlatBufferBuilder builder, int[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateEquipidxsVectorBlock(FlatBufferBuilder builder, ArraySegment<int> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateEquipidxsVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<int>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartEquipidxsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddUnitdatas(FlatBufferBuilder builder, VectorOffset unitdatasOffset) { builder.AddOffset(1, unitdatasOffset.Value, 0); }
  public static VectorOffset CreateUnitdatasVector(FlatBufferBuilder builder, Offset<BanpoFri.Data.UnitData>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateUnitdatasVectorBlock(FlatBufferBuilder builder, Offset<BanpoFri.Data.UnitData>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateUnitdatasVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<BanpoFri.Data.UnitData>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateUnitdatasVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<BanpoFri.Data.UnitData>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartUnitdatasVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<BanpoFri.Data.UnitGroupData> EndUnitGroupData(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<BanpoFri.Data.UnitGroupData>(o);
  }
  public UnitGroupDataT UnPack() {
    var _o = new UnitGroupDataT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(UnitGroupDataT _o) {
    _o.Equipidxs = new List<int>();
    for (var _j = 0; _j < this.EquipidxsLength; ++_j) {_o.Equipidxs.Add(this.Equipidxs(_j));}
    _o.Unitdatas = new List<BanpoFri.Data.UnitDataT>();
    for (var _j = 0; _j < this.UnitdatasLength; ++_j) {_o.Unitdatas.Add(this.Unitdatas(_j).HasValue ? this.Unitdatas(_j).Value.UnPack() : null);}
  }
  public static Offset<BanpoFri.Data.UnitGroupData> Pack(FlatBufferBuilder builder, UnitGroupDataT _o) {
    if (_o == null) return default(Offset<BanpoFri.Data.UnitGroupData>);
    var _equipidxs = default(VectorOffset);
    if (_o.Equipidxs != null) {
      var __equipidxs = _o.Equipidxs.ToArray();
      _equipidxs = CreateEquipidxsVector(builder, __equipidxs);
    }
    var _unitdatas = default(VectorOffset);
    if (_o.Unitdatas != null) {
      var __unitdatas = new Offset<BanpoFri.Data.UnitData>[_o.Unitdatas.Count];
      for (var _j = 0; _j < __unitdatas.Length; ++_j) { __unitdatas[_j] = BanpoFri.Data.UnitData.Pack(builder, _o.Unitdatas[_j]); }
      _unitdatas = CreateUnitdatasVector(builder, __unitdatas);
    }
    return CreateUnitGroupData(
      builder,
      _equipidxs,
      _unitdatas);
  }
}

public class UnitGroupDataT
{
  [Newtonsoft.Json.JsonProperty("equipidxs")]
  public List<int> Equipidxs { get; set; }
  [Newtonsoft.Json.JsonProperty("unitdatas")]
  public List<BanpoFri.Data.UnitDataT> Unitdatas { get; set; }

  public UnitGroupDataT() {
    this.Equipidxs = null;
    this.Unitdatas = null;
  }
}


static public class UnitGroupDataVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyVectorOfData(tablePos, 4 /*Equipidxs*/, 4 /*int*/, false)
      && verifier.VerifyVectorOfTables(tablePos, 6 /*Unitdatas*/, BanpoFri.Data.UnitDataVerify.Verify, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
