// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace BanpoFri.Data
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct UnitData : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_5_26(); }
  public static UnitData GetRootAsUnitData(ByteBuffer _bb) { return GetRootAsUnitData(_bb, new UnitData()); }
  public static UnitData GetRootAsUnitData(ByteBuffer _bb, UnitData obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public UnitData __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int Unitidx { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public bool MutateUnitidx(int unitidx) { int o = __p.__offset(4); if (o != 0) { __p.bb.PutInt(o + __p.bb_pos, unitidx); return true; } else { return false; } }
  public int Unitlevel { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public bool MutateUnitlevel(int unitlevel) { int o = __p.__offset(6); if (o != 0) { __p.bb.PutInt(o + __p.bb_pos, unitlevel); return true; } else { return false; } }

  public static Offset<BanpoFri.Data.UnitData> CreateUnitData(FlatBufferBuilder builder,
      int unitidx = 0,
      int unitlevel = 0) {
    builder.StartTable(2);
    UnitData.AddUnitlevel(builder, unitlevel);
    UnitData.AddUnitidx(builder, unitidx);
    return UnitData.EndUnitData(builder);
  }

  public static void StartUnitData(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddUnitidx(FlatBufferBuilder builder, int unitidx) { builder.AddInt(0, unitidx, 0); }
  public static void AddUnitlevel(FlatBufferBuilder builder, int unitlevel) { builder.AddInt(1, unitlevel, 0); }
  public static Offset<BanpoFri.Data.UnitData> EndUnitData(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<BanpoFri.Data.UnitData>(o);
  }
  public UnitDataT UnPack() {
    var _o = new UnitDataT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(UnitDataT _o) {
    _o.Unitidx = this.Unitidx;
    _o.Unitlevel = this.Unitlevel;
  }
  public static Offset<BanpoFri.Data.UnitData> Pack(FlatBufferBuilder builder, UnitDataT _o) {
    if (_o == null) return default(Offset<BanpoFri.Data.UnitData>);
    return CreateUnitData(
      builder,
      _o.Unitidx,
      _o.Unitlevel);
  }
}

public class UnitDataT
{
  [Newtonsoft.Json.JsonProperty("unitidx")]
  public int Unitidx { get; set; }
  [Newtonsoft.Json.JsonProperty("unitlevel")]
  public int Unitlevel { get; set; }

  public UnitDataT() {
    this.Unitidx = 0;
    this.Unitlevel = 0;
  }
}


static public class UnitDataVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Unitidx*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 6 /*Unitlevel*/, 4 /*int*/, 4, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
